import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import FilterCountries from "../components/FilterCountries";
import Navbar from "../components/Navbar";
import SearchInput from "../components/SearchInput";

const URL = "https://restcountries.com/v2/all";

export const getStaticProps = async () => {
  const res = await fetch(URL);
  const countries = await res.json();
  return {
    props: { countries },
  };
};

export default function Home({ countries }) {
  const [keyword, setKeyword] = useState("");
  const [selectedRegion, setSelectedRegion] = useState("default");
  const handleChange = (e) => {
    setKeyword(e.target.value);
  }

  const handleRegionChange = (e) => {
    setSelectedRegion(e.target.value);
  }

  return (
    <div>
      <Head>
        <title>Countries Finder App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <section className="content-wrapper">
        <section className="search-wrapper">
        <SearchInput onChange={handleChange} value={keyword} />
        <FilterCountries onChange={handleRegionChange} value={selectedRegion} />
        </section>
        <div className="country-list">
        {countries.filter((country) => {
          if (keyword) {
            return (country.name.toLowerCase().includes(keyword.toLowerCase()))
          } else if (selectedRegion !== "default") {
            return (country.region.toLowerCase().includes(selectedRegion.toLowerCase()))
          }
          return country;
        }).map((country) => {
          return (
            <div className="country-item" key={country.id}>
              <img src={country.flag} alt={`${country.name} flag`}/>
              <div className="country-item_content">
              <h3>{country.name}</h3>
              <p><span>Population:</span> {country.population.toLocaleString('en-US')}</p>
              <p><span>Region:</span> {country.region}</p>
              <p><span>Capital:</span> {country.capital}</p>
              </div>
            </div>
          );
        })}
        {/* {countries.map((country) => {
          return (
            <div className="country-item" key={country.id}>
              <img src={country.flag} />
              <div className="country-item_content">
              <h3>{country.name}</h3>
              <p><span>Population:</span> {country.population.toLocaleString('en-US')}</p>
              <p><span>Region:</span> {country.region}</p>
              <p><span>Capital:</span> {country.capital}</p>
              </div>
            </div>
          );
        })} */}
        </div>
        </section>
      </main>
    </div>
  );
}
